### ISSUE TITLE
`chmod +x` is unnecessary

### ISSUE THREAD

**Issue by egoist** [uetchy/create-create-app#16]
`chmod +x lib/cli.js` is unnecessary:

https://github.com/uetchy/create-create-app/blob/76488945e2ab05fbcc4df779cfa239fdc8412a14/package.json#L7

tsup does that for you:

https://github.com/egoist/tsup/blob/aabb5027219ca99cef0e7aa4085989bf7531fc04/src/index.ts#L100-L103

**Comment by uetchy** [comment]
@egoist Thank you for letting me know about that. Very convenient and intuitive☺️
