### ISSUE TITLE
allow to use UNLICENSED for license

### ISSUE THREAD

**Issue by takahashim** [uetchy/create-create-app#22]
I would like to create private apps using this tool, especially with [vivliostyle/create-book](https://github.com/vivliostyle/create-book).

In [documents of npm](https://docs.npmjs.com/files/package.json), we can use `{ "license": "UNLICENSED" }` for private packages.  So I think it would be a good idea to support this specification in create-create-app as well.

Consideration:

* Should we support this feature in default, or using `extra` arguments in `create()`?
* When choosing UNLICENSED, should we also add `{"private": true}` in package.json?

**Comment by takahashim** [comment]
See also #23.

**Comment by uetchy** [comment]
> Should we support this feature in default?
Yes, as long as npm officially supports it.

> should we also add {"private": true} in package.json?
I feel like it beyond our project scope. Whether publish unlicensed package or not is up to users.

Having said that, adding UNLICENSED to the license list is a good idea!

**Comment by takahashim** [comment]
OK, I made a PR #25.
