### ISSUE TITLE
Prefer `pnpm` if available 

### ISSUE THREAD

**Issue by herberthobregon** [uetchy/create-create-app#29]
Could you add `pnpm` if available? or can choose  like `pkgManager: ['pnpm','yarn','npm']` in config

It could be in the settings. or ask the user depending on what options you have installed on your system

**Comment by uetchy** [comment]
<img width="599" alt="Screen Shot 2022-03-26 at 15 35 40" src="https://user-images.githubusercontent.com/431808/160227937-16b532ee-847b-4a0e-a5f0-da538193da14.png">
🤔

**Comment by uetchy** [comment]
Added `--node-pm` cli param but

> It could be in the settings. or ask the user depending on what options you have installed on your system

^ still missing the interactive question thing. Consider opening a new issue or PR for this.
