### ISSUE TITLE
Skip install? template variables in file names?

### ISSUE THREAD

**Issue by lucas-labs** [uetchy/create-create-app#41]
Hi! Thanks for sharing this great library.

I would like to ask two questions:

1. Is it possible to skip `npm install` at the end of the creation?  If the template has a package.json, at the end of the creation process, it will automatically install packages. Is there any way to avoid package install?

2. Is it possible to use variables for file names? I'm trying to do this but something weird happens:

This is my template folder with a variable on one filename.
![image](https://user-images.githubusercontent.com/12949236/175819251-cab512dc-08c4-4f01-9cee-42ee20087b2c.png)

This results in the following output. Notice that test is appended at the start of the filename, and also, the file is not even inside the created folder, but one directory behind.

![image](https://user-images.githubusercontent.com/12949236/175819354-fbb5a56d-1224-4e65-81bc-1e705ff65184.png)

Thanks!!

**Comment by uetchy** [comment]
Fixed in [v7.3.0](https://github.com/uetchy/create-create-app/releases/tag/v7.3.0)
